# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KOoibiDgKoTJN64Zq7G9S0mgVWnNw_Lz
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load the data
df = pd.read_csv('DataCoSupplyChainDataset.csv', encoding='latin1')
df.head()

# Remove columns that are 100% empty
df.dropna(axis=1, how='all', inplace=True)

# Convert order dates to a usable format
df['order_date'] = pd.to_datetime(df['order date (DateOrders)'])
print("Data Cleaning Complete!")

# Create a 'is_late' column (1 = Late, 0 = On Time)
df['is_late'] = (df['Days for shipping (real)'] > df['Days for shipment (scheduled)']).astype(int)

# Calculate the percentage of late orders
late_percentage = df['is_late'].mean() * 100
print(f"BMW Supply Chain Health: {late_percentage:.2f}% of orders are late.")

# Find the late rate for each region
region_stats = df.groupby('Order Region')['is_late'].mean().sort_values(ascending=False)

# Create a chart
plt.figure(figsize=(12,6))
region_stats.plot(kind='bar', color='blue')
plt.title('Logistics Delays by Region (BMW Intern Project)')
plt.ylabel('Percentage of Late Orders')
plt.show()